name: Minecraft AFK Bot

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *' # بيشتغل تلقائياً كل 5 ساعات

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 345 # بيقفل الـ Job أوتوماتيك بعد 5 ساعات و 45 دقيقة (قبل حد الـ 6 ساعات)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Start Bot
        run: node --max-old-space-size=256 index.js
