name: Minecraft AFK Bot

on: 
  workflow_dispatch:

concurrency:
  group: minecraft-afk-bot
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Start Bot
        run: node index.js
